<?xml version="1.0" encoding="UTF-8"?><testrun name="TestMatrixPublic" project="16" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="tests.TestMatrixPublic" time="10.018" displayname="TestMatrixPublic" uniqueid="[engine:junit-vintage]/[runner:tests.TestMatrixPublic]">
    <testcase name="testc3" classname="tests.TestMatrixPublic" time="10.018" displayname="testc3" uniqueid="[engine:junit-vintage]/[runner:tests.TestMatrixPublic]/[test:testc3(tests.TestMatrixPublic)]">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds&#13;
	at java.base@16.0.1/java.util.PriorityQueue.siftDownComparable(PriorityQueue.java:698)&#13;
	at java.base@16.0.1/java.util.PriorityQueue.poll(PriorityQueue.java:583)&#13;
	at java.base@16.0.1/java.util.AbstractQueue.remove(AbstractQueue.java:113)&#13;
	at app//code.Queue.PrQ.dequeue(PrQ.java:20)&#13;
	at app//code.GeneralSearch.generalSearch(GeneralSearch.java:180)&#13;
	at app//code.Matrix.solve(Matrix.java:302)&#13;
	at app//tests.TestMatrixPublic.testc3(TestMatrixPublic.java:278)&#13;
	at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)&#13;
	at java.base@16.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base@16.0.1/java.lang.reflect.Method.invoke(Method.java:567)&#13;
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#13;
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#13;
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)&#13;
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)&#13;
	at java.base@16.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#13;
	at java.base@16.0.1/java.lang.Thread.run(Thread.java:831)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
